#!/bin/bash

readonly GIT="git"

readonly status="status"
readonly branch="branch"
readonly checkout="checkout"
readonly commit="commit"
readonly push="push"
readonly add="add"
readonly pull="pull"
readonly tag="tag"

readonly HIDDEN_FILE=".hidden"
readonly commit_flags_a="-a"
readonly commit_flags_m="m"
readonly push_flags="-u"
readonly branch_flags="-D"
readonly tag_flags="-d"
readonly tag_push_delete_flags=":refs/tags/"
readonly tag_push_all_flags="--tags"

readonly origin="origin"

readonly main_branch="main" #TODO: read this from .config

function git_branch(){
    if [[ $# -eq 1 ]]; then
        ${GIT} ${branch} "${1}"
    else
        ${GIT} ${branch}    
    fi
}

function git_checkout(){
    ${GIT} ${checkout} "${1}"
}

function git_commit(){
    ${GIT} ${commit} "${commit_flags_a}""${commit_flags_m}" "${1}"
}

function git_push(){
    ${GIT} ${push} "${push_flags}" "${origin}" "${1}"
}

function git_status(){
    ${GIT} ${status}
}

function file_create_control(){
    if [ ! -f $HIDDEN_FILE ]; then
        file_create
    else
        file_remove
    fi
}

#file
function file_create(){
    echo " " > $HIDDEN_FILE
    file_add
}

function file_remove(){
    rm $HIDDEN_FILE
}

function file_add(){
    ${GIT} ${add} $HIDDEN_FILE
}

function branch_create(){
    git_branch "${1}"
}

function branch_delete_all(){
    for to_delete in $(git_branch); do
        if [[ $to_delete != "$main_branch" ]]; then
            ${GIT} ${branch} ${branch_flags} "${to_delete}"
        fi
    done
}

function get_main(){
    git_checkout ${main_branch}
    ${GIT} ${pull}
}

function tag_copy(){
    ${GIT} ${tag} "${1}" "${2}"
}

function tag_delete(){
    ${GIT} ${tag} ${tag_flags} "${1}"
}

function tag_push_deleted(){
    ${GIT} ${push} ${origin} ${tag_push_delete_flags}"${1}"
}

function tag_push_all(){
    ${GIT} ${push} ${tag_push_all_flags}
}

function increment_send(){
    ${GIT} ${commit} "${commit_flags_a}""${commit_flags_m}" "${1}"
    ${GIT} ${push}
}
