#!/bin/bash

source common.sh

gb_arg=$1

if [[ $# -eq 1 ]]; then
    if [ "$gb_arg" = "-d" ]; then
        common::branch_delete_all
    else
        # * * creates a new branch
        common::branch_create "$gb_arg"

        # * * checks out the new branch
        common::git_checkout "$gb_arg"

        #TODO: these two lines from above can be replaced with "git checkout -b branch_name"

        # * * makes some update
        common::file_create_control

        # * * commits the "initial commit"
        common::git_commit "initial commit"

        # * * pushes to the upstream
        common::git_push "$gb_arg"
    fi
else
    common::git_branch
fi